### ISSUE TITLE
Create Alert Component

### ISSUE THREAD

**Issue by Pearlsky** [chingu-voyages/v43-tier3-team-36#63]

**Comment by Pearlsky** [comment]
@TazDeCoder please, how do I make the alert layout available for both the auth and other app pages? I'm not sure I can use the Layout component that requires SEO props, I'm not sure if the auth pages need those. I might be getting sth wrong, idk

**Comment by TazDeCoder** [comment]
> @TazDeCoder please, how do I make the alert layout available for both the auth and other app pages? I'm not sure I can use the Layout component that requires SEO props, I'm not sure if the auth pages need those. I might be getting sth wrong, idk

You need to use the layout component - and yes you need to specify the **SEOO props** - please refer to other pages to see that it's not difficult. 

To get the **Alert** component rendered into the page, you will need to add them into layout themselves.

**Comment by Pearlsky** [comment]
okay, I've taken note of the SEO Props. the thing is, I need the alert component not to be tied to each page. suppose a user is redirected to the profile page after authentication. In that case, the alert component that begins on the auth page and informs a user of successful auth shouldn't disappear on being redirected to the profile page. idk if you get me

**Comment by TazDeCoder** [comment]
Can you just commit what changes you've made into the linked branch for this issue and make a PR for it so I can what you've done so far.

From the best of my understanding, I can suggest here to just create this component in the `ui` folder because initially I had thought that this wasn't a generic **Alert** component - from the look of it - it is and therefore this approach allows you to create another component in the `components/common` folder where you can add the logic to get the store state of the alert and use that to render whatever message is rendered in it.

I hope this make sense and therefore you can follow through with my recommendation.

**Comment by Pearlsky** [comment]
> Can you just commit what changes you've made into the linked branch for this issue and make a PR for it so I can see what you've done so far.
> 
> From what I've gathered so far, I can suggest here to just create this component in the `ui` folder because initially I had thought that this wasn't a generic **Alert** component - however, from the looks of it - it is and therefore this approach allows you to also create another component in the `components/common` folder where you can import this ui component and add the logic to get the store state of the alert and use that to render whatever message is in it and render it in.
> 
> I hope this make sense and therefore you can follow through with my recommendation.

This definitely makes sense. commit and PR done.
