### ISSUE TITLE
Update Label Component 

### ISSUE THREAD

**Issue by Pearlsky** [chingu-voyages/v43-tier3-team-36#83]
**__Task Description__**
The color for this component is currently specific and I'd like to update this component to make the styling more flexible

**Comment by Pearlsky** [comment]
> If your referring to **Chip** component, there already is an option to pass in a **className** prop to the component so that you can override the default color - let me know if you have any issues with that

@TazDeCoder I'm well aware of that option, I used it, and it worked for some classes, & didn't work for some. Upon research, turns out it's a pretty common problem that **it's not in all cases that classes passed in the **className** prop** (or any other classes-receiving props), **override the already applied tailwind classes**.

Kindly refer to the following for your understanding:
- [ Override styles via React props and classnames library](https://github.com/tailwindlabs/discuss/issues/360)
- [tailwind css custom class passed as props are not overriding the already applied class](https://stackoverflow.com/questions/72887137/tailwind-css-custom-class-passed-as-props-is-not-overriding-the-already-applied)
- [TailwindCSS 3 classes doesn't override previous classes](https://stackoverflow.com/questions/72148525/tailwindcss-3-classes-doesnt-override-previous-classes)

I'd kindly suggest that we either use a utility library like **tw-merge** or **take out the base styling for appearance properties** - `bg`, `text-color` and let that be dynamically set by whoever is using the component.

**Comment by TazDeCoder** [comment]
Okay cool, now that I understand this common issue, I would prefer that we go with the **tw-merge** option since we don't want to completely remove essential styling props like `bg` and `text-color` because we may just prefer the default color scheme in some cases. 

This method means we can still have the previous implementation, but without having to worry about adding extra props to component for no reason other than to change a **very specific classname** for that component
